### ISSUE TITLE
Question: why use _alloc?

### ISSUE THREAD

**Issue by adipose** [ShiftMediaProject/libass#4]
Can you explain your changes to the libass code like the below:

![image](https://user-images.githubusercontent.com/3324395/84167900-a82c1b80-aa2b-11ea-9bf4-cf9621260e46.png)

Is it to do with WINRT?

**Comment by Sibras** [comment]
It was used because its functionally identical. MSVC doesnt support dynamic array sizing (a C99 feature) so it cant compile 'mul[max_subdiv + 1]'. This line of code just allocates a 'max_subdiv + 1' sized section of memory on the stack for the duration of the function. So the changed line of code does exactly the same thing (alloca to allocate stack memory) just using syntax that msvc can actually compile.

**Comment by adipose** [comment]
Interesting.  In later sources it was changed to:

    enum { max_subdiv = 15 };
    double mul[max_subdiv + 1];

Apparently the same problem is not present with enum as a constant int, as this compiles in VS. It's not really dynamic if it is hardcoded in a const int, but I guess msvc couldn't tell that.

**Comment by Sibras** [comment]
Yep, enums are compile time constants whereas a const variable is not (this is why c++ added constexpr variables as those are compile time constants).

**Comment by adipose** [comment]
FYI, using latest sources, and MSVC 2019, I require no changes to the libass source to compile (I am not using WINRT).

The enum solution is simpler, and perhaps while not exactly "functionally equivalent," it should in theory behave identically, so maybe it's a cleaner code change until a new release comes out.  It has the added benefit of being consistent with newer libass sources, fwtw.

Thanks for explaining the change.
