### ISSUE TITLE
Cannot create .winmd file

### ISSUE THREAD

**Issue by rmtjokar** [ShiftMediaProject/libass#8]
Make this better and add extra info.

Hi, 
First, I want to thank you for this and all other projects.

I'm trying to build this for UWP, I actually managed to build it but there is no winmd file in entire folders.
I've edited the `smp_winrt_deps.props` files to ensure winmd creates properly:

```
      <AdditionalUsingDirectories>$(WindowsSDK_WindowsMetadata);$(AdditionalUsingDirectories)</AdditionalUsingDirectories>
      <!-- <MinimumRequiredVersion Condition="'$(ApplicationTypeRevision)' == '10.0'">10.0</MinimumRequiredVersion>-->
      <!--<MinimumRequiredVersion Condition="'$(ApplicationTypeRevision)' == '8.1'">8.1</MinimumRequiredVersion>-->
      <WindowsMetadataFile>$(ProjectDir)..\..\..\msvc\x64\$(RootNamespace).winmd</WindowsMetadataFile>
      <GenerateWindowsMetadata>true</GenerateWindowsMetadata>
```
As you can see by commenting above codes, I managed to atleast create a X64 folder but there is no winmd file.

P.S: None of the configuration can make winmd file.

Can you please help me?
Thanks in advance 

## Your Environment
* Version Used: latest github clone
* Operating System and Version: Windows 11 build 22631.4317
* Compiler and Version(s): v143
* VS version: 2022 v17.11.5

**Comment by Sibras** [comment]
The project doesnt actually consume any window runtime components as its a native C project. As a sresult there is nothing to export in the winmd file which is why one is never created as its essentially empty. If your having issues then this is most likely due to VS still enabling the linker output option for winmd even though theres nothing to do (Linker->Windows metadata->Gneerate windows metadat). Ill disable that in the projects

**Comment by rmtjokar** [comment]
Thank you for your information
